### ISSUE TITLE
Pergunta: Poderia explicar melhor o que cada coluna do db representa?

### ISSUE THREAD

**Issue by amadeu01** [marinalimeira/rails-coffee-shop#3]
Não entendi o que cada coluna representa. Tipo o significa `ground`?
Também não entedi o link que você fez entre as duas tabelas product e sales. Poderia explicar um pouco melhor?

**Comment by marinalimeira** [comment]
Oi!

`ground` é o tipo de moagem do grão. Como o app é para gerenciar pacotes de café, o banco foi baseado nesse produto.

Sobre a ligação entre as tabelas, eu acho que ficou confuso porque a imagem tava errada. Atualizei a [imagem no repositório](https://github.com/marinalimeira/rails-coffee-shop/blob/gh-pages/images/db_diagram.png) e acho que agora faz mais sentido. Interpretando essa imagem, o campo `product_id` está referenciando a tabela `products`, já que é uma chave estrangeira.

**Comment by amadeu01** [comment]
@marinalimeira Obrigado! Fez mais sentido agora!

**Comment by amadeu01** [comment]
@marinalimeira 
Uma coisa a mais hahaha.
roast é tipo uma escala ?
Tipo torra media/ torra clara ?

**Comment by marinalimeira** [comment]
@amadeu01 exatamente! Vou atualizar isso no repo tb :)

**Comment by amadeu01** [comment]
É que tipo, poderia ser um `enum`, ou uma escala. Quando compro café, eles tem uma especie de escala de 0-10 e colocam a torra lá em uma escalinhas

0=========10
------ˆ
Torra média

0=========10
-------------ˆ
Torra forte 

Algo do gênero

**Comment by marinalimeira** [comment]
Eita, curti!

Vou criar um TO-DO pra adicionar isso, e ainda mostrando como utilizar o `change_column` e alterar o tipos no banco pra `integer`. :D
