### ISSUE TITLE
Funcionalidade de Login

### ISSUE THREAD

**Issue by amadeu01** [marinalimeira/rails-coffee-shop#4]
- Poderia ter uma forma de login para um usuário (Vendedor) do coffee shop executar ações, seria legal até saber quem fez o que:
    - 1. Quem vendeu o produto,
    - 2. Quem adicionou o produto no estoque. 
- Como um agente externo (um aplicativo iOS, Android) poderia fazer login? Que tipo de autenticação usaria?

**Comment by amadeu01** [comment]
Achei um link bem legal que fala de rails e iOS
[link](https://www.raywenderlich.com/85528/user-accounts-ios-ruby-rails-swift)

**Comment by marinalimeira** [comment]
Oie!

- Sobre a funcionalidade de login:
A gente pode utilizar o [Devise](https://github.com/plataformatec/devise). Ele cuida de toda parte de autenticação, gerenciar cookies de sessão e ainda salva a senha criptografada no banco :) boa parte da comunidade utiliza ele em produção, então é sucesso :)
  - a. utilizando o  Devise, teremos acesso a um objeto chamado `current_user` no controller, que referencia o objeto de `User` que está fazendo a requisição. Podemos adicionar um campo `sold_by` a `Sale` e na ação do controller que vai salvar a venda, a gente adiciona isso!
  - b. ^mesma coisa pra `Product`. A gente pode adicionar um `created_by` (ou `updated_by`? fica a dúvida se você gostaria de saber quem fez a última atualização ou a primeira, ou ambas).

- Pra fazer autenticação com o app, eu utilizo o [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper), o fluxo seria mais ou menos assim:
  **->** app envia usuário e senha pro servidor
  **->** servidor verifica se usuário/senha estão corretos; se sim, retorna um token de acesso (que normalmente expira, você define quando isso acontece)
  **->** :tada: você guarda esse token na app e adiciona ele em toda requisição que fizer.
Aí o servidor sempre valida esse token e se for válido você consegue fazer as requests de boas, caso contrário, retorna [401](https://httpstatuses.com/401).

**Comment by marinalimeira** [comment]
Curti a ideia da autenticação, irei adicionar um TODO :)

**Comment by marinalimeira** [comment]
Tenho um [repo de exemplo de um workshop](https://github.com/marinalimeira/collaborative-playlist-api/tree/master/app/controllers/api/v1) que dei há uns tempos, é de uma API que faz acesso a [uma app em React](https://github.com/marinalimeira/collaborative-playlist-app), os controllers tem um `doorkeeper_authorize!` pra validar as requisições.

Documentação tá 0, mas se tiver dúvidas, fique a vontade o/

**Comment by amadeu01** [comment]
não sei se vou conseguir olhar nesse final de semana. mas, vou deixar um
lembrete para olhar depois!
